# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    
    strategy:
      matrix:
        profile: [ win-x64, win-arm64, osx-x64, osx-arm64, linux-x64, linux-arm64 ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: src/packages.lock.json
    - name: Restore dependencies
      run: dotnet restore src/ --locked-mode
    - name: Build
      run: dotnet build src/ --no-restore --configuration Release
    - name: Publish 
      run: dotnet publish src/ --no-build /p:PublishProfile=${{ matrix.profile }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.profile }} binary
        path: artifacts/publish/github-release-downloader/release_${{ matrix.profile }}/*
