# This workflow doesn't work for now as GitHub runners don't have the necessary toolchain for cross architecture builds
# I keep it to maybe use self-hosted runners later when I will have enough machines 

name: .NET Cross-Architecture Publish

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner'
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - self-hosted, Linux
          - self-hosted, Windows
          - self-hosted, macOS
      arch:
        description: 'Build Architecture'
        required: true
        default: x64
        type: choice
        options:
          - x64
          - arm64

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:

    runs-on: ${{ github.workflow.inputs.runner }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: src/packages.lock.json
    - name: Restore dependencies
      run: dotnet restore src/
    - name: Publish
      run: dotnet publish src/ --no-restore --arch ${{ github.workflow.inputs.arch }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }} ${{ runner.arch }} binary
        path: artifacts/publish/github-release-downloader/release*/**/*
 