# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    
    strategy:
      matrix:
        runner:
          - os: ubuntu-latest
            pid: linux
          - os: windows-latest
            pid: win
          - os: macos-latest
            pid: osx
        architecture:
          - x64
          - arm64

    runs-on: ${{ matrix.runner.os }}
 
    env:
      RID: ${{ matrix.runner.pid }}-${{ matrix.architecture }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: src/packages.lock.json
    - name: Restore dependencies
      run: dotnet restore src/
    # - name: Build
    #   run: dotnet build src/ --no-restore --runtime ${{ env.RID }} --configuration Release
    - name: Publish
      run: dotnet publish src/ --no-restore --runtime ${{ env.RID }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RID }} binary
        path: artifacts/publish/github-release-downloader/release_${{ env.RID }}/**/*
 